#155965575 configure periodic report sending
andela/hc-bigas-opus pull request #12
Opened 2018-03-29 06:17 UTC by frankip

#### What does this PR do?
Create periodic times to send out reports
#### Description of Task to be completed?
user should be able to choose the times he wants to receive their reports on checks they have
#### How should this be manually tested?
clone the repo, checkout to `ft-configure-periodic-reports-155965575` branch
install the requirements run `migrate` command `python manage.py migrate`
then navigate to the profile page and select the periodic you want to receive the report
#### What are the relevant pivotal tracker stories?
#155965575
#### Screenshots
<img width="595" alt="screen shot 2018-03-29 at 09 15 55" src="https://user-images.githubusercontent.com/19773670/38073053-fe6fc83e-3331-11e8-83e5-9fb5d1bd732a.png">

2018-03-29 10:04 UTC, lakivisi-zz requested changes

2018-03-29 10:04 UTC, Loice-Andia commented on hc/accounts/views.py
> +                print(profile.next_report_date)
remove print statements; code cleanup

2018-03-29 10:04 UTC, Loice-Andia commented on hc/accounts/views.py
> +# time_passed = now - profile.next_report_date
remove commented code

2018-03-29 10:04 UTC, Loice-Andia commented on templates/accounts/profile.html
> +                    <!-- <label>
remove commented code

2018-03-29 10:04 UTC, Loice-Andia commented on templates/accounts/profile.html
> +                        <option value="daily" {% if profile.reports_frequency == 'daily' %} selected {% endif %}> daily</option>
PEP 8 standards; no more than 79 characters

2018-04-03 12:16 UTC, mutoromike commented
Great job including the new features enabling sending of immediate, daily and weekly reports onto the existing one (monthly). If you could just comment on the added features in your code, it will be great. An example is given below:
`+                        <input name="reports_allowed" value='daily' type="radio"
+                            {% if profile.reports_allowed == 'daily' %} checked {% endif %}>
+                            daily
                     </label>
+                    <label>
+                        <input name="reports_allowed" value='weekly' type="radio" 
+                        {% if profile.reports_allowed == 'weekly' %} checked {% endif %}>
+                        weekly
+                    </label>
+                    <label>
+                        <input name="reports_allowed" value='monthly' type="radio" 
+                        {% if profile.reports_allowed == 'monthly' %} checked {% endif %}>
+                        Monthly
+                    </label>
+`

This is just one of them. Thanks.

2018-04-03 14:42 UTC, meshnesh commented on templates/accounts/dashboard.html
> +{% extends "base.html" %}
good Implementation of the dashboard

2018-04-03 14:42 UTC, meshnesh commented on hc/api/management/commands/sendreports.py
> +        month_before = now - timedelta(days=1)
should the time delta be in single day rather than days, since it's a single day

2018-04-03 14:42 UTC, meshnesh commented on hc/accounts/views.py
> +@login_required
awesome implementation

2018-04-03 14:42 UTC, meshnesh commented on hc/accounts/tests/test_profile.py
> +    def test_you_can_view_report(self):
nice implementation

2018-04-03 17:21 UTC, frankip commented on hc/api/management/commands/sendreports.py
> +        month_before = now - timedelta(days=1)
timedelta does not support the argument day but instead it uses days

2018-04-03 19:53 UTC, Kalela commented on hc/accounts/views.py
> +    return render(request, 'accounts/dashboard.html', ctx)
Great job implementing the dashboard logic.

2018-04-03 21:03 UTC, lakivisi-zz approved these changes

2018-04-03 21:04 UTC, merged